@QuickShop.Server_HostAddress = https://localhost:7188

GET {{QuickShop.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{QuickShop.Server_HostAddress}}/api/categories

###

GET {{QuickShop.Server_HostAddress}}/api/categories

###
